// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/jinsoft/ainiok/app/user/cmd/api/internal/handler/user"
	"github.com/jinsoft/ainiok/app/user/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/v1"),
	)
}
