// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
}
